name: Build Android Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Libérer de l'espace sur le serveur
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false # On garde Android bien sûr !
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Configurer Node.js et le Cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configurer Java 17 et le Cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Installer les dépendances
        run: npm install

      - name: Générer le dossier Android (Prebuild)
        run: npx expo prebuild --platform android --clean

      - name: Décoder le Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/release.keystore

      - name: Compiler et signer le Bundle Android (.aab)
        run: |
          cd android
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Sauvegarder le fichier .aab
        uses: actions/upload-artifact@v4
        with:
          name: Ganbanaaxu-Release
          path: android/app/build/outputs/bundle/release/*.aab